name = "batfd_plus_default"
num_frames = 512  # T
max_duration = 40  # D
model_type = "batfd_plus"
dataset = "lavdf"

[model.video_encoder]
type = "mvit_b"
hidden_dims = []  # handled by model type
cla_feature_in = 256  # C_f

[model.audio_encoder]
type = "vit_b"
hidden_dims = []  # handled by model type
cla_feature_in = 256  # C_f

[model.frame_classifier]
type = "lr"

[model.boundary_module]
hidden_dims = [512, 128]
samples = 10  # N

[optimizer]
learning_rate = 0.00001
frame_loss_weight = 2.0
modal_bm_loss_weight = 1.0
cbg_feature_weight = 0.0
prb_weight_forward = 1.0
contrastive_loss_weight = 0.1
contrastive_loss_margin = 0.99
weight_decay = 0.0001

[soft_nms]
alpha = 0.7234
t1 = 0.1968
t2 = 0.4123
